horizontal_menu: main
horizontal_depth: 2
off_canvas_menus: main
horizontal_wrapping_element: nav
horizontal_breakpoint: wide
horizontal_media_query: '(min-width: 728px)'
include_css: true
off_canvas_position: left
off_canvas_theme: theme-light
horizontal_superfish: true
horizontal_superfish_delay: 300
horizontal_superfish_speed: 100
horizontal_superfish_speed_out: 100
horizontal_superfish_hoverintent: true
hammerjs: true
breakpoint_css_filepath: 'public://css'
use_breakpoint: true
_core:
  default_config_hash: VQrlRTddOlJMvm8KmJK_1kKkuyprhNp9okQAxKmKs6c
