<?php
// Plugin definition
$plugin = array(
  'title' => t('Rome'),
  'icon' => 'rome.png',
  'category' => t('Panelitist'),
  'theme' => 'panels_rome',
  'css' => '../../../css/panels/rome/rome.css',
  'regions' => array(
    'contentheader' => t('Content Header'),
    'sidebar' => t('Right Rail for Ads'),
    'left_rail' => t('Left Rail'),
    'content_row_1' => t('Content Row 1'),
    'content_row_2' => t('Content Row 2'),
    'content_row_3' => t('Content Row 3'),
    'content_row_4' => t('Content Row 4'),
    'content_row_5' => t('Content Row 5'),
    'content_row_6' => t('Content Row 6'),
    'content_row_7' => t('Content Row 7'),
    'content_row_8' => t('Content Row 8'),
    'footer' => t('Footer'),
  ),
);
