<?php
// Plugin definition
$plugin = array(
  'title' => t('London'),
  'icon' => 'london.png',
  'category' => t('Panelitist'),
  'theme' => 'london',
  'css' => '../../../css/panels/london/london.css',
  'regions' => array(
    'header' => t('Header'),
    'headercontent' => t('HeaderContent'),
    'column1' => t('First Column'),
    'column2' => t('Second Column'),
    'footer' => t('Footer'),
  ),
);
